//////////////////////////////////////////

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OFgro ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

//////////////////////////////////////////

= TinkerPop Podling Maturity Assessment

== Overview

This is an assessment of the TinkerPop podling's maturity, meant to help inform
the decision (of the mentors, community, Incubator PMC and ASF Board of 
Directors) to graduate it as a top-level Apache project.

It is based on the ASF project maturity model at
https://community.apache.org/apache-way/apache-project-maturity-model.html


== Status of this document
All items resolved.

== Overall assessment
Most of the below items are marked OK, TinkerPop seems close to being ready to graduate.

== Maturity model assessment 
(Mentors and community members are encouraged to contribute to this 
and comment on it.)

=== Code

==== CD10
_The project produces Open Source software, for distribution to the public at no charge._

OK: Yes.
 
==== CD20
_The project's code is easily discoverable and publicly accessible._

OK: http://tinkerpop.apache.org/ (see CO10) includes both links to downloads and GitHub presence.

==== CD30
_The code can be built in a reproducible way using widely available standard tools._

OK: CI is used on new commits, binary convenience packages available as is the source, documentation exists on how to build it.

==== CD40
_The full history of the project's code is available via a source code control system, in a way that allows any released version to be recreated._

OK: Using Git, main repository at https://git-wip-us.apache.org/repos/asf/incubator-tinkerpop.git - releases are cut from that repository.

==== CD50
_The provenance of each line of code is established via the source code control system, in a reliable way based on strong authentication of the committer.
When third-party contributions are committed, commit messages provide reliable information about the code provenance._

OK: see CD40 

=== Licenses and Copyright

==== LC10
_The code is released under the Apache License, version 2._0._ 

OK: LICENSE file has been accepted in release votes. Checked for ASF/ALv2 compliance on every release and passed.

==== LC20
_Libraries that are mandatory dependencies of the project's code do not create more restrictions than the Apache License does._

OK: The list of dependencies at https://wiki.apache.org/incubator/TinkerpopProposal has been verified when entering incubation.

The current dependency licenses (including build, runtime and optional dependencies) are found at
https://github.com/apache/incubator-tinkerpop/tree/master/LICENSE

Release reviews have not shown any incompatible or missing licenses.

==== LC30
_The libraries mentioned in LC20 are available as Open Source software._

OK: see LC20 

==== LC40
_Committers are bound by an Individual Contributor Agreement (the "Apache iCLA") that defines which code they are allowed to commit and how they need to identify code that is not their own._

OK: All committers have iCLAs on file. 

==== LC50
_The copyright ownership of everything that the project produces is clearly defined and documented._

OK: Quite obvious for an ASF project.

=== Releases

==== RE10
_Releases consist of source code, distributed using standard and open archive formats that are expected to stay readable in the long term._

OK: verified in release votes. Convenience binary packages also available.

==== RE20
_Releases are approved by the project's PMC (see CS10), in order to make them an act of the Foundation._

OK: Releases have been voted by the Incubator PMC as well as the PPMC. 

==== RE30
_Releases are signed and/or distributed along with digests that can be reliably used to validate the downloaded archives._

OK: Verified in release votes. 

==== RE40
_Convenience binaries can be distributed alongside source code but they are not Apache Releases -- they are just a convenience provided with no guarantee._

OK: https://dist.apache.org/repos/dist/release/incubator/tinkerpop/3.1.1-incubating/ for example clearly differentiates between source releases and binary distributions. There is are immediate links to source downloads from the web site.

=== Quality

==== QU10
_The project is open and honest about the quality of its code. Various levels of quality and maturity for various modules are natural and acceptable as long as they are clearly communicated._ 

OK: TinkerPop has a long history of being a good citizen about quality.

==== QU20
_The project puts a very high priority on producing secure software._

OK: see QU10

==== QU30
_The project provides a well-documented channel to report security issues, along with a documented way of responding to them._

OK: Project links to the generic security team.

==== QU40
_The project puts a high priority on backwards compatibility and aims to document any incompatible changes and provide tools and documentation to help users transition to new features._ 

OK, see QU10.

==== QU50
_The project strives to respond to documented bug reports in a timely manner._

OK: Response times on the users list, PRs and jira are very good. 

=== Community

==== CO10
_The project has a well-known homepage that points to all the information required to operate according to this maturity model._

OK: http://tinkerpop.apache.org/ 

==== CO20
_The community welcomes contributions from anyone who acts in good faith and in a respectful manner and adds value to the project._ 

OK: The community is working well in this respect. 

==== CO30
_Contributions include not only source code, but also documentation, constructive bug reports, constructive discussions, marketing and generally anything that adds value to the project._

OK: Tinkerpop has elected some non-coding committers, marketing people, designers etc.

==== CO40
_The community is meritocratic and over time aims to give more rights and responsibilities to contributors who add value to the project._

OK: TinkerPop has elected a few committers during incubation. 

==== CO50
_The way in which contributors can be granted more rights such as commit access or decision power is clearly documented and is the same for all contributors._

OK: based on the standard ASF docs. 

==== CO60
_The community operates based on consensus of its members (see CS10) who have decision power. Dictators, benevolent or not, are not welcome in Apache projects._

OK: Demonstrated during incubation. 

==== CO70
_The project strives to answer user questions in a timely manner._

OK: See QU50. 

=== Consensus Building

==== CS10
_The project maintains a public list of its contributors who have decision power -- the project's PMC (Project Management Committee) consists of those contributors._

OK: Will be at https://home.apache.org/phonebook.html?ctte=tinkerpop once the project graduates. 

==== CS20
_Decisions are made by consensus among PMC members and are documented on the project's main communications channel. Community opinions are taken into account but the PMC has the final word if needed._

OK: the TinkerPop team has been making and documenting decisions on its dev list during incubation.

==== CS30
_Documented voting rules are used to build consensus when discussion is not sufficient._ 

OK: using the standard ASF voting process, http://www.apache.org/foundation/voting.html

==== CS40
_In Apache projects, vetoes are only valid for code commits and are justified by a technical explanation, as per the Apache voting rules defined in CS30._

OK: Vetoes haven't been abused during incubation. 

==== CS50
_All "important" discussions happen asynchronously in written form on the project's main communications channel. Offline, face-to-face or private discussions that affect the project are also documented on that channel._

OK: see CS20. 

=== Independence

==== IN10
_The project is independent from any corporate or organizational influence._

OK: No such influence has been detected during incubation. 

==== IN20
_Contributors act as themselves as opposed to representatives of a corporation or organization._

OK: No worrying signals here during incubation.
